version: '3'

services:
  web:
    build: ./
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000-8000
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
