# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('date', models.DateField()),
                ('filename', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('preview', models.TextField()),
                ('content', models.TextField()),
                ('file_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('url_name', models.CharField(max_length=128)),
            ],
        ),
    ]
