# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='filename',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
