# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file_hash',
        ),
    ]
