# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20171125_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('static_path', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
    ]
